linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gosec
    - misspell
    - prealloc
    - revive
    - stylecheck

linters-settings:
  goimports:
    local-prefixes: github.com/bmorphism/vibespace-mcp-go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - examples
  skip-files:
    - ".*\\.pb\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true