name: Quick Tests

# Lightweight test workflow for quick feedback
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GO_VERSION: '1.24'

jobs:
  quick-test:
    name: Quick Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Download dependencies
      run: |
        go mod download
        go mod verify

    - name: Run fast tests
      run: |
        go test -short -race ./...

    - name: Check build
      run: |
        go build -v ./...

  # Quick format and basic lint check
  quick-lint:
    name: Quick Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Check formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted properly:"
          gofmt -s -l .
          exit 1
        fi

    - name: Run go vet
      run: go vet ./...

    - name: Check for common issues
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...
